repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest stable version of flake8
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5  # Use the latest stable version of pylint
    hooks:
      - id: pylint

  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: pytest
        language: system
        always_run: true
        pass_filenames: false
